/*
 * 苏州小学现行译林版英语的分册词表。
 *
 * 三年级上册以译林出版社教材 Word lists 第 78～80 页为准，生词、短语、重要句型
 * 和带 * 的非单元核心词全部收录，共 127 项；其余分册暂时仍是每单元 8 个第一阶段
 * 核心词。修订版教材逐年滚动启用，所以每册都有独立版本号和 NVS 键；换版或由
 * 核心集升级为完整词表时，新旧进度不会被错误地当成同一套词。
 */

#include "word_study_data.h"

#define U(n, w, m) { (w), (m), (n) - 1 }
#define WORDS_COUNT(a) ((uint16_t)(sizeof(a) / sizeof((a)[0])))

static const study_word_t G3A[] = {
    U(1, "hello", "哈啰; 你好"), U(1, "hi", "喂; 嗨"),
    U(1, "Good morning.", "早上好"), U(1, "I", "我"),
    U(1, "am", "是"), U(1, "ah", "啊"),
    U(1, "a", "一(个)"), U(1, "cat", "猫"),
    U(1, "Miss", "小姐; 女士"), U(1, "Good afternoon.", "下午好"),
    U(1, "class", "同学们"), U(1, "goodbye", "再见; 再会"),
    U(1, "bye", "再见; 再会"),

    U(2, "what", "什么"), U(2, "is", "是"),
    U(2, "your", "你的; 你们的"), U(2, "name", "名字"),
    U(2, "my", "我的"), U(2, "Nice to meet you!", "很高兴认识你"),
    U(2, "too", "也"), U(2, "boy", "男孩"),
    U(2, "and", "和; 与"), U(2, "girl", "女孩"),
    U(2, "Mr (AmE Mr.)", "先生"),

    U(3, "are", "是"), U(3, "you", "你; 你们"),
    U(3, "no", "不; 不是"), U(3, "not", "不; 没有"),
    U(3, "yes", "是; 对"), U(3, "ha", "笑声; 哈"),
    U(3, "Here I am!", "我在这里"), U(3, "but", "但是"),
    U(3, "oh", "啊; 哦"), U(3, "sorry", "对不起"),
    U(3, "twin", "双胞胎之一"), U(3, "we", "我们"),
    U(3, "excuse me", "对不起"), U(3, "class", "班级"),
    U(3, "in", "在...内; 在...中"), U(3, "with", "和; 同"),
    U(3, "right", "正确的"),

    U(4, "this", "这; 这个"), U(4, "friend", "朋友"),
    U(4, "she", "她"), U(4, "he", "他"),
    U(4, "it", "它"), U(4, "good", "好的"),
    U(4, "Thank you.", "谢谢你"), U(4, "have", "有; 持有"),
    U(4, "many", "许多"),

    U(5, "mother", "母亲; 妈妈"), U(5, "father", "父亲; 爸爸"),
    U(5, "dad", "爸爸"), U(5, "mum (AmE mom)", "妈妈"),
    U(5, "brother", "哥哥; 弟弟"), U(5, "baby", "婴儿"),
    U(5, "sister", "姐姐; 妹妹"), U(5, "Good evening.", "晚上好"),
    U(5, "quick", "快; 快点"), U(5, "look", "看; 瞧"),
    U(5, "the", "这个; 这些; 那个; 那些"), U(5, "pond", "池塘; 水池"),
    U(5, "who", "谁; 什么人"), U(5, "great", "极好的; 好棒的"),
    U(5, "come", "来"), U(5, "meet", "相识; 结识; 被引见介绍"),
    U(5, "family", "家; 家庭"), U(5, "say", "说"),

    U(6, "grandfather (grandpa)", "祖父; 外祖父"),
    U(6, "uncle", "舅叔伯姑姨父"), U(6, "aunt", "舅婶伯姑姨母"),
    U(6, "grandmother (grandma)", "祖母; 外祖母"),
    U(6, "cousin", "堂表兄弟姐妹"), U(6, "cool", "妙极的; 酷的"),
    U(6, "me", "我"), U(6, "wow", "哇; 呀"),
    U(6, "big", "大的"), U(6, "it", "指性别不详的婴儿"),
    U(6, "happy", "幸福的"), U(6, "love", "爱; 热爱"),

    U(7, "Happy Birthday!", "生日快乐"), U(7, "one", "一"),
    U(7, "two", "二"), U(7, "three", "三"),
    U(7, "four", "四"), U(7, "five", "五"),
    U(7, "six", "六"), U(7, "seven", "七"),
    U(7, "eight", "八"), U(7, "nine", "九"),
    U(7, "ten", "十"), U(7, "now", "现在; 此刻"),
    U(7, "want", "要; 想要"), U(7, "car", "小汽车; 轿车"),
    U(7, "book", "书"), U(7, "ball", "球"),
    U(7, "cake", "蛋糕; 糕饼"), U(7, "How lovely!", "真可爱"),
    U(7, "Can I help you?", "要帮忙吗"), U(7, "Yes, please.", "好的; 谢谢"),
    U(7, "some", "一些"), U(7, "toy", "玩具"),
    U(7, "for", "给; 对; 供"), U(7, "OK", "对; 好; 行"),
    U(7, "How old are you?", "你多大了"), U(7, "please", "请"),
    U(7, "here", "到这里; 在这里"), U(7, "love", "喜好; 喜爱"),
    U(7, "Here you are.", "给你"), U(7, "You're welcome.", "别客气; 不用谢"),
    U(7, "thanks", "谢谢"),

    U(8, "can", "能; 会"), U(8, "do", "做; 干; 办(某事)"),
    U(8, "for", "为了"), U(8, "clean", "使干净; 打扫"),
    U(8, "table", "桌子"), U(8, "draw", "画; 描画"),
    U(8, "sing", "唱歌; 演唱"), U(8, "take pictures", "拍照"),
    U(8, "dance", "跳舞"), U(8, "Are you OK?", "你没事吧"),
    U(8, "dizzy", "头晕目眩的; 眩晕的"), U(8, "picture", "图画; 绘画; 照片"),
    U(8, "er", "哦; 嗯"), U(8, "fox", "狐狸"),
    U(8, "child (pl. children)", "儿童; 小孩"), U(8, "thing", "事情"),
};

static const study_word_t G3B[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "school", "学校"), U(1, "pen", "钢笔"),
    U(1, "pencil", "铅笔"), U(1, "ruler", "直尺"),
    U(1, "rubber", "橡皮"), U(1, "schoolbag", "书包"),
    U(1, "pencil case", "铅笔盒"), U(1, "that", "那; 那个"),
    U(2, "our", "我们的"), U(2, "classroom", "教室"),
    U(2, "close", "关闭"), U(2, "window", "窗户"),
    U(2, "blackboard", "黑板"), U(2, "chair", "椅子"),
    U(2, "sweep", "打扫"), U(2, "floor", "地板; 地面"),
    U(3, "rule", "规则"), U(3, "library", "图书馆"),
    U(3, "talk", "说话"), U(3, "eat", "吃"),
    U(3, "run", "跑"), U(3, "Mrs", "太太; 夫人"),
    U(3, "sit down", "坐下"), U(3, "late", "迟的; 晚的"),
    U(4, "have fun", "玩得高兴"), U(4, "after class", "课后"),
    U(4, "behind", "在后面"), U(4, "tree", "树"),
    U(4, "by", "在旁边"), U(4, "under", "在下面"),
    U(4, "flower", "花"), U(4, "play", "玩耍"),
    U(5, "fruit", "水果"), U(5, "orange", "橙子"),
    U(5, "grape", "葡萄"), U(5, "banana", "香蕉"),
    U(5, "apple", "苹果"), U(5, "mango", "芒果"),
    U(5, "share", "分享"), U(5, "like", "喜欢"),
    U(6, "farm", "农场"), U(6, "cow", "奶牛"),
    U(6, "sheep", "绵羊"), U(6, "rabbit", "兔子"),
    U(6, "chicken", "鸡"), U(6, "carrot", "胡萝卜"),
    U(6, "pig", "猪"), U(6, "home", "家; 住所"),
    U(7, "animal", "动物"), U(7, "monkey", "猴子"),
    U(7, "lion", "狮子"), U(7, "bear", "熊"),
    U(7, "tiger", "老虎"), U(7, "panda", "大熊猫"),
    U(7, "elephant", "大象"), U(7, "fish", "鱼; 鱼肉"),
    U(8, "colour", "颜色"), U(8, "yellow", "黄色的"),
    U(8, "blue", "蓝色的"), U(8, "red", "红色的"),
    U(8, "orange", "橙色的"), U(8, "pink", "粉红色的"),
    U(8, "green", "绿色的"), U(8, "brown", "棕色的"),
};

static const study_word_t G4A[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "subject", "学科; 科目"), U(1, "Chinese", "语文课"),
    U(1, "English", "英语课"), U(1, "Maths", "数学课"),
    U(1, "PE", "体育课"), U(1, "Art", "美术课"),
    U(1, "Science", "科学课"), U(1, "Music", "音乐课"),
    U(2, "day", "一天; 一日"), U(2, "get up", "起床"),
    U(2, "wash", "洗"), U(2, "face", "脸; 面孔"),
    U(2, "have lessons", "上课"), U(2, "have dinner", "吃晚饭"),
    U(2, "breakfast", "早餐"), U(2, "lunch", "午餐"),
    U(3, "week", "周; 星期"), U(3, "Monday", "星期一"),
    U(3, "Tuesday", "星期二"), U(3, "Wednesday", "星期三"),
    U(3, "Thursday", "星期四"), U(3, "Friday", "星期五"),
    U(3, "Saturday", "星期六"), U(3, "Sunday", "星期日"),
    U(4, "play", "打球; 踢球"), U(4, "football", "足球"),
    U(4, "ping-pong", "乒乓球"), U(4, "basketball", "篮球"),
    U(4, "great", "非常的"), U(4, "swimming", "游泳"),
    U(4, "well", "好"), U(4, "try", "试"),
    U(5, "hair", "头发"), U(5, "eye", "眼睛"),
    U(5, "ear", "耳朵"), U(5, "nose", "鼻子"),
    U(5, "mouth", "嘴"), U(5, "arm", "手臂"),
    U(5, "leg", "腿"), U(5, "robot", "机器人"),
    U(6, "weather", "天气"), U(6, "cloudy", "多云的"),
    U(6, "sunny", "晴朗的"), U(6, "cool", "凉爽的"),
    U(6, "rainy", "多雨的"), U(6, "hot", "热的"),
    U(6, "windy", "多风的"), U(6, "warm", "温暖的"),
    U(7, "season", "季节"), U(7, "spring", "春天"),
    U(7, "go boating", "去划船"), U(7, "winter", "冬天"),
    U(7, "summer", "夏天"), U(7, "ice cream", "冰激凌"),
    U(7, "go swimming", "去游泳"), U(7, "autumn", "秋天"),
    U(8, "wear", "穿; 戴"), U(8, "cap", "便帽"),
    U(8, "coat", "外套"), U(8, "skirt", "半身裙"),
    U(8, "trousers", "裤子"), U(8, "dress", "连衣裙"),
    U(8, "shirt", "男式衬衫"), U(8, "shorts", "短裤"),
};

static const study_word_t G4B[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "school", "学校"), U(1, "subject", "课程"),
    U(1, "Welcome back", "欢迎回来"), U(1, "see", "看见"),
    U(1, "timetable", "课程表"), U(1, "Chinese", "语文课"),
    U(1, "Maths", "数学课"), U(1, "Art", "美术课"),
    U(2, "after school", "放学后"), U(2, "go", "去"),
    U(2, "What day is it", "星期几"), U(2, "Wednesday", "星期三"),
    U(2, "match", "比赛"), U(2, "today", "今天"),
    U(2, "Saturday", "星期六"), U(2, "Sunday", "星期日"),
    U(3, "usually", "通常"), U(3, "go to school", "上学"),
    U(3, "in the morning", "在上午"), U(3, "have lunch", "吃午饭"),
    U(3, "in the afternoon", "在下午"), U(3, "play football", "踢足球"),
    U(3, "go home", "回家"), U(3, "homework", "家庭作业"),
    U(4, "drawing", "画画"), U(4, "park", "公园"),
    U(4, "draw", "画"), U(4, "Good idea", "好主意"),
    U(4, "flower", "花"), U(4, "them", "他们; 她们; 它们"),
    U(4, "easy", "容易的"), U(4, "boat", "小船"),
    U(5, "season", "季节"), U(5, "spring", "春天"),
    U(5, "warm", "温暖的"), U(5, "fly", "放飞"),
    U(5, "kite", "风筝"), U(5, "go boating", "去划船"),
    U(5, "summer", "夏天"), U(5, "hot", "炎热的"),
    U(6, "dress", "连衣裙"), U(6, "too", "太; 过于"),
    U(6, "trousers", "裤子"), U(6, "party", "聚会"),
    U(6, "glove", "手套"), U(6, "so", "如此; 这么"),
    U(6, "coat", "外套"), U(6, "shirt", "男式衬衫"),
    U(7, "What's the matter", "怎么了"), U(7, "tired", "累的"),
    U(7, "ill", "生病的"), U(7, "thirsty", "渴的"),
    U(7, "water", "水"), U(7, "happy", "开心的"),
    U(7, "speak", "说话"), U(7, "Mrs", "太太; 夫人"),
    U(8, "may", "可以"), U(8, "come to school", "来学校"),
    U(8, "cold", "感冒"), U(8, "fever", "发烧"),
    U(8, "hear", "听见"), U(8, "take care", "保重"),
    U(8, "at school", "在学校"), U(8, "headache", "头疼"),
};

static const study_word_t G5A[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "bear", "熊"), U(1, "forest", "森林"),
    U(1, "there", "有"), U(1, "house", "房子"),
    U(1, "soup", "汤"), U(1, "just right", "正合适"),
    U(1, "room", "房间"), U(1, "hard", "硬的"),
    U(2, "student", "学生"), U(2, "show around", "带领参观"),
    U(2, "classroom", "教室"), U(2, "second", "第二"),
    U(2, "floor", "楼层"), U(2, "computer", "电脑"),
    U(2, "third", "第三"), U(2, "first", "第一"),
    U(3, "one, the other", "一个; 另一个"), U(3, "body", "身体"),
    U(3, "no", "没有"), U(3, "leg", "腿"),
    U(3, "or", "也不"), U(3, "arm", "手臂"),
    U(3, "wing", "翅膀"), U(3, "foot", "脚"),
    U(4, "hobby", "业余爱好"), U(4, "be good at", "擅长"),
    U(4, "with", "与一起"), U(4, "also", "也"),
    U(4, "read", "阅读"), U(4, "story", "故事"),
    U(4, "a lot of", "很多"), U(4, "play the piano", "弹钢琴"),
    U(5, "teacher", "老师"), U(5, "teach", "教"),
    U(5, "writer", "作家"), U(5, "write", "写"),
    U(5, "work", "工作"), U(5, "at home", "在家"),
    U(5, "doctor", "医生"), U(5, "help", "帮助"),
    U(6, "e-friend", "网友"), U(6, "Wait a minute", "等一会儿"),
    U(6, "send", "发出"), U(6, "email", "电子邮件"),
    U(6, "to", "给"), U(6, "live", "居住"),
    U(6, "UK", "英国"), U(6, "years old", "岁"),
    U(7, "at weekends", "在周末"), U(7, "visit", "拜访; 参观"),
    U(7, "grandparent", "祖父母; 外祖父母"), U(7, "play with", "和一起玩"),
    U(7, "very much", "非常"), U(7, "often", "经常"),
    U(7, "chat", "聊天"), U(7, "Internet", "互联网"),
    U(8, "Christmas", "圣诞节"), U(8, "buy", "买"),
    U(8, "present", "礼物"), U(8, "Christmas tree", "圣诞树"),
    U(8, "Father Christmas", "圣诞老人"), U(8, "next", "接着"),
    U(8, "put", "放"), U(8, "pretty", "漂亮的"),
};

static const study_word_t G5B[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "prince", "王子"), U(1, "fairy", "仙女"),
    U(1, "why", "为什么"), U(1, "because", "因为"),
    U(1, "clothes", "衣服"), U(1, "let", "让"),
    U(1, "put on", "穿上"), U(1, "before", "在以前"),
    U(2, "far from", "离很远"), U(2, "moon", "月亮"),
    U(2, "street", "街道"), U(2, "near", "在附近"),
    U(2, "city", "城市"), U(2, "by bus", "乘公共汽车"),
    U(2, "on foot", "步行"), U(2, "metro", "地铁"),
    U(3, "ask the way", "问路"), U(3, "get to", "到达"),
    U(3, "take", "搭乘"), U(3, "get on", "上车"),
    U(3, "station", "车站"), U(3, "get off", "下车"),
    U(3, "walk", "步行"), U(3, "bookshop", "书店"),
    U(4, "see the doctor", "看医生"), U(4, "feel", "感觉"),
    U(4, "check", "检查"), U(4, "should", "应该"),
    U(4, "have a rest", "休息"), U(4, "take medicine", "吃药"),
    U(4, "drink water", "喝水"), U(4, "toothache", "牙疼"),
    U(5, "parent", "父亲或母亲"), U(5, "clean", "擦; 洗"),
    U(5, "cook", "烧; 煮"), U(5, "sweep the floor", "扫地"),
    U(5, "busy", "忙碌的"), U(5, "wash the dishes", "洗碗"),
    U(5, "make the bed", "整理床铺"), U(5, "grow", "种植"),
    U(6, "game", "运动; 比赛"), U(6, "smell", "有气味"),
    U(6, "meat", "肉"), U(6, "vegetable", "蔬菜"),
    U(6, "tomato", "西红柿"), U(6, "potato", "土豆"),
    U(6, "I can't wait", "我等不及了"), U(6, "look for", "寻找"),
    U(7, "festival", "节日"), U(7, "Spring Festival", "春节"),
    U(7, "January", "一月"), U(7, "February", "二月"),
    U(7, "call", "叫作"), U(7, "Chinese New Year", "中国农历新年"),
    U(7, "get together", "团聚"), U(7, "jiaozi", "饺子"),
    U(8, "birthday", "生日"), U(8, "eleventh", "第十一"),
    U(8, "eighth", "第八"), U(8, "April", "四月"),
    U(8, "together", "一起"), U(8, "game", "游戏"),
    U(8, "March", "三月"), U(8, "July", "七月"),
};

static const study_word_t G6A[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "long long ago", "很久以前"), U(1, "magic", "有魔力的"),
    U(1, "clever", "聪明的"), U(1, "foolish", "愚蠢的"),
    U(1, "through", "穿过"), U(1, "laugh", "大笑"),
    U(1, "wear", "穿"), U(1, "tell", "讲述"),
    U(2, "sunny", "晴朗的"), U(2, "show", "展览"),
    U(2, "interesting", "有趣的"), U(2, "weather", "天气"),
    U(2, "become", "变成"), U(2, "windy", "有风的"),
    U(2, "cloudy", "多云的"), U(2, "high", "在高处"),
    U(3, "holiday", "假日"), U(3, "National Day", "国庆节"),
    U(3, "call", "打电话"), U(3, "Bund", "上海外滩"),
    U(3, "Shanghai Museum", "上海博物馆"), U(3, "star", "星星"),
    U(3, "Great Wall", "长城"), U(3, "Palace Museum", "故宫"),
    U(4, "then and now", "过去和现在"), U(4, "ago", "以前"),
    U(4, "use", "使用"), U(4, "telephone", "电话"),
    U(4, "office", "办公室"), U(4, "mobile phone", "手机"),
    U(4, "anywhere", "随处"), U(4, "radio", "收音机"),
    U(5, "sign", "标识"), U(5, "shopping centre", "购物中心"),
    U(5, "careful", "小心"), U(5, "What does it mean", "它是什么意思"),
    U(5, "mean", "意思是"), U(5, "floor", "地面"),
    U(5, "litter", "乱扔垃圾"), U(5, "go in", "进入"),
    U(6, "keep", "保持"), U(6, "clean", "干净的"),
    U(6, "make", "使变得"), U(6, "air", "空气"),
    U(6, "dirty", "肮脏的"), U(6, "smoke", "烟雾"),
    U(6, "rubbish", "垃圾"), U(6, "messy", "乱七八糟的"),
    U(7, "protect", "保护"), U(7, "Earth", "地球"),
    U(7, "save", "节约"), U(7, "useful", "有用的"),
    U(7, "much", "很多"), U(7, "waste", "浪费"),
    U(7, "reuse", "再利用"), U(7, "energy", "能源"),
    U(8, "get", "收到"), U(8, "Hong Kong", "香港"),
    U(8, "next week", "下周"), U(8, "food", "食物"),
    U(8, "tangyuan", "汤圆"), U(8, "New Year's Eve", "除夕"),
    U(8, "New Year's Day", "大年初一"), U(8, "red packet", "红包"),
};

static const study_word_t G6B[STUDY_STANDARD_DECK_WORDS] = {
    U(1, "mouse", "老鼠"), U(1, "large", "大的"),
    U(1, "strong", "强壮的"), U(1, "walk by", "走过"),
    U(1, "wake up", "吵醒"), U(1, "some day", "某一天"),
    U(1, "quietly", "小声地"), U(1, "weak", "弱的"),
    U(2, "habit", "习惯"), U(2, "never", "从不"),
    U(2, "late", "迟; 晚"), U(2, "put in order", "整理好"),
    U(2, "finish", "完成"), U(2, "tidy", "整齐的"),
    U(2, "bad", "不好的"), U(2, "sleepy", "困倦的"),
    U(3, "healthy", "健康的"), U(3, "diet", "饮食"),
    U(3, "a little", "一点"), U(3, "a few", "几个"),
    U(3, "at a time", "一次"), U(3, "cola", "可乐"),
    U(3, "need", "需要"), U(3, "vegetable", "蔬菜"),
    U(4, "road", "马路"), U(4, "safety", "安全"),
    U(4, "cross", "穿过"), U(4, "safely", "安全地"),
    U(4, "must", "必须"), U(4, "zebra crossing", "斑马线"),
    U(4, "safe", "安全的"), U(4, "pavement", "人行道"),
    U(5, "Children's Day", "儿童节"), U(5, "clown", "小丑"),
    U(5, "appear", "出现"), U(5, "balloon", "气球"),
    U(5, "begin", "开始"), U(5, "put on", "上演"),
    U(5, "end", "结束"), U(5, "month", "月"),
    U(6, "country", "国家"), U(6, "will", "将要"),
    U(6, "learn", "学习"), U(6, "Australia", "澳大利亚"),
    U(6, "find out", "发现"), U(6, "magazine", "杂志"),
    U(6, "kangaroo", "袋鼠"), U(6, "koala", "考拉"),
    U(7, "summer holiday", "暑假"), U(7, "go back to", "回去"),
    U(7, "how long", "多久"), U(7, "stay", "停留"),
    U(7, "sound", "听起来"), U(7, "Disneyland", "迪士尼乐园"),
    U(7, "Ocean Park", "海洋公园"), U(7, "Taipei", "台北"),
    U(8, "dream", "梦想"), U(8, "future", "将来"),
    U(8, "care about", "关心"), U(8, "tooth", "牙齿"),
    U(8, "astronaut", "宇航员"), U(8, "spaceship", "宇宙飞船"),
    U(8, "football player", "足球运动员"), U(8, "World Cup", "世界杯"),
};

const study_deck_t STUDY_DECKS[STUDY_DECK_COUNT] = {
    { "g3a24full", 3, true,  "2024新课标", { "问候", "姓名", "确认身份", "介绍朋友", "家庭成员", "大家庭", "生日", "帮助家人" }, G3A, WORDS_COUNT(G3A) },
    { "g3b24", 3, false, "2024新课标", { "学习用品", "打扫教室", "校园规则", "课后活动", "水果", "农场", "动物", "颜色" }, G3B, WORDS_COUNT(G3B) },
    { "g4a25", 4, true,  "2025新课标", { "学科", "一天作息", "一周计划", "体育运动", "外貌", "天气", "四季", "服装" }, G4A, WORDS_COUNT(G4A) },
    { "g4b13", 4, false, "2013版", { "学校课程", "课后", "我的一天", "公园画画", "季节", "化装舞会", "身体感受", "打电话" }, G4B, WORDS_COUNT(G4B) },
    { "g5a14", 5, true,  "2014版", { "金发女孩", "新同学", "动物朋友", "爱好", "职业", "网友", "周末", "圣诞节" }, G5A, WORDS_COUNT(G5A) },
    { "g5b14", 5, false, "2014版", { "灰姑娘", "上学方式", "问路", "看医生", "帮助父母", "厨房", "中国节日", "生日" }, G5B, WORDS_COUNT(G5B) },
    { "g6a14", 6, true,  "2014版", { "皇帝的新衣", "天气", "假日趣事", "过去与现在", "公共标识", "城市环境", "保护地球", "中国新年" }, G6A, WORDS_COUNT(G6A) },
    { "g6b14", 6, false, "2014版", { "狮子和老鼠", "好习惯", "健康饮食", "道路安全", "派对", "有趣的国家", "暑假计划", "梦想" }, G6B, WORDS_COUNT(G6B) },
};

_Static_assert(WORDS_COUNT(G3A) == 127, "三上完整词表数量错误");
_Static_assert(WORDS_COUNT(G3B) == STUDY_STANDARD_DECK_WORDS, "三下核心词数量错误");
_Static_assert(WORDS_COUNT(G4A) == STUDY_STANDARD_DECK_WORDS, "四上核心词数量错误");
_Static_assert(WORDS_COUNT(G4B) == STUDY_STANDARD_DECK_WORDS, "四下核心词数量错误");
_Static_assert(WORDS_COUNT(G5A) == STUDY_STANDARD_DECK_WORDS, "五上核心词数量错误");
_Static_assert(WORDS_COUNT(G5B) == STUDY_STANDARD_DECK_WORDS, "五下核心词数量错误");
_Static_assert(WORDS_COUNT(G6A) == STUDY_STANDARD_DECK_WORDS, "六上核心词数量错误");
_Static_assert(WORDS_COUNT(G6B) == STUDY_STANDARD_DECK_WORDS, "六下核心词数量错误");
